### PR TITLE
Testimony UI material

### PR DESCRIPTION
**Pull request by Zyanvel**
Hi guys, I am testing pull requests with the testimony component (which is kind of done), could you please check it out? Thank you both so much for your attention :)

### CODE REVIEW

**Comment by spagnon7** [comment]
Looks good to me, thanks

**Comment by Zyanvel** [comment]
Hi Sean and Albert, could any of you please review the changes, approve them and finally merge them into the main branch? Thank you so much!

**Review by milkdudss — COMMENTED** [review]
Looking good!

**Review by spagnon7 — APPROVED** [review]
Looks like maybe Ineed to do this review submittal too. Looks good to me.

**Pull request merged**
